// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The OCX Authors

//! Writing the generated files, and the `--check` comparison against what is
//! already on disk.
//!
//! Action pins are mirror-repo-owned: the comparison strips `@<ref>` from
//! every `uses:` line so a downstream Renovate bump does not trip the guard,
//! while keeping the `owner/action` identity so swapping in a different
//! action still reds.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use super::slot::slash_path;
use crate::error::MirrorError;

/// Write all rendered files to disk under `repo_root`.
///
/// Creates parent directories as needed. Uses `tokio::fs::write` which is
/// atomic from the caller's perspective (single write call per file).
pub async fn write_files(files: &BTreeMap<PathBuf, String>, repo_root: &Path) -> Result<(), MirrorError> {
    for (relative_path, content) in files {
        let dest = repo_root.join(relative_path);
        if let Some(parent) = dest.parent() {
            tokio::fs::create_dir_all(parent).await.map_err(|e| {
                MirrorError::TemplateError(format!("failed to create directory {}: {e}", parent.display()))
            })?;
        }
        tokio::fs::write(&dest, content)
            .await
            .map_err(|e| MirrorError::TemplateError(format!("failed to write {}: {e}", dest.display())))?;
    }
    Ok(())
}

/// Matches a `uses:` action-reference line so its *pin* can be normalized away
/// before drift comparison. Group `keep` holds the `uses: owner/action` head; the
/// `@<ref>` is matched only when `<ref>` is **pin-shaped** — a single run of
/// non-space, non-`#` characters (a digest or tag) optionally followed by a
/// `# vX` version comment — and that suffix is dropped. A `uses:` line carrying
/// anything else after the ref (shell metacharacters, a second token, inline
/// `with:`-like text) does NOT match, so such a hand-edit still trips drift
/// rather than being masked. Per-line anchored (`(?m)`); matches both `- uses:`
/// list items and bare `uses:` step keys.
///
/// The regex is line-oriented and YAML-unaware: it would also match an indented
/// `uses: owner/action@<ref>` line *inside* a `run:` block scalar. No current
/// template emits such a line — keep it that way (do not emit `run:` block lines
/// beginning with `uses: …@…`) or the pin on that script line would be masked.
pub static USES_REF_RE: std::sync::LazyLock<regex::Regex> = std::sync::LazyLock::new(|| {
    regex::Regex::new(r"(?m)^(?P<keep>[ \t]*(?:-[ \t]+)?uses:[ \t]*[^@\s]+)@[^\s#]+(?:[ \t]*#[^\n]*)?$").unwrap()
});

/// Canonicalize a generated workflow for drift comparison.
///
/// Mirror repositories own the *pin* on every `uses:` action reference: their
/// own Renovate/Dependabot may bump `uses: owner/action@<ref>  # vX` and the
/// drift guard must not treat that as a hand-edit. The guard still polices the
/// workflow *logic* and *which* action each step runs — only the `@<ref>` suffix
/// (digest or tag, plus any trailing version comment) is stripped; the
/// `owner/action` identity is preserved, so swapping in a different action still
/// trips drift. The baked template ships a known-good seed pin for first render.
pub fn normalize_for_drift(content: &str) -> std::borrow::Cow<'_, str> {
    USES_REF_RE.replace_all(content, "${keep}")
}

/// First line of every file this renderer writes.
pub const GENERATED_HEADER: &str = "# Generated by ocx-mirror";

/// Generated workflows on disk that the current spec set no longer renders.
///
/// Dropping a spec leaves its workflows behind, and a mirror workflow whose
/// spec no longer exists keeps running on schedule against a spec that is gone.
/// Only files carrying the generated header are considered, so a repository's
/// hand-written workflows are never touched.
pub async fn stale_generated(files: &BTreeMap<PathBuf, String>, repo_root: &Path) -> Vec<String> {
    let workflows_dir = repo_root.join(".github/workflows");
    let Ok(mut entries) = tokio::fs::read_dir(&workflows_dir).await else {
        return Vec::new();
    };

    let mut stale = Vec::new();
    while let Ok(Some(entry)) = entries.next_entry().await {
        let path = entry.path();
        if !path.extension().is_some_and(|ext| ext == "yml" || ext == "yaml") {
            continue;
        }
        let Ok(relative) = path.strip_prefix(repo_root) else {
            continue;
        };
        if files.contains_key(relative) {
            continue;
        }
        if tokio::fs::read_to_string(&path)
            .await
            .is_ok_and(|content| content.starts_with(GENERATED_HEADER))
        {
            stale.push(slash_path(relative));
        }
    }
    stale.sort();
    stale
}

/// Compare the expected generated files against what is on disk.
///
/// Returns `RendererDrift` if any file is missing, has different content — after
/// normalizing `uses:` action pins on both sides (see [`normalize_for_drift`]) —
/// or is a generated workflow no spec renders any more. Drift hints are
/// path-only — never expose file contents to stderr (secret-hygiene rule R3).
pub async fn check_drift(files: &BTreeMap<PathBuf, String>, repo_root: &Path) -> Result<(), MirrorError> {
    let mut drifted: Vec<String> = Vec::new();

    for (relative_path, expected) in files {
        let on_disk_path = repo_root.join(relative_path);
        match tokio::fs::read_to_string(&on_disk_path).await {
            Ok(actual) => {
                if normalize_for_drift(&actual) != normalize_for_drift(expected) {
                    // Emit path-only hint; content never printed (R3).
                    eprintln!("drift: {}", relative_path.display());
                    drifted.push(relative_path.display().to_string());
                }
            }
            Err(_) => {
                // Missing file counts as drift.
                eprintln!("drift: {}", relative_path.display());
                drifted.push(relative_path.display().to_string());
            }
        }
    }

    for path in stale_generated(files, repo_root).await {
        eprintln!("stale: {path}");
        drifted.push(path);
    }

    if drifted.is_empty() {
        Ok(())
    } else {
        Err(MirrorError::RendererDrift(drifted))
    }
}
