[schema]
enabled = true

[[rule]]
include = [
  "**/.config/ocx/config.toml",
  "**/.ocx/config.toml",
  "**/ocx/config.toml",
]
url = "https://ocx.sh/schemas/config/v1.json"

[[rule]]
include = [
  "**/ocx.toml",
]
url = "https://ocx.sh/schemas/project/v1.json"
